version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    registries:
      - private-nexus
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
