server.port: 8080

spring:
  application:
    name: eden-research
  threads.virtual:
    enabled: true

app:
  web:
    jira-url: https://paramount.atlassian.net
    regon-url: https://wyszukiwarkaregon.stat.gov.pl
  regon:
    api-key: ${REGON_API_KEY:abcde12345abcde12345}

logging:
  #structured.format.console: ecs
  level:
    root: INFO
    org.springframework.web: DEBUG
    tech.paramount: DEBUG

