server.port: ${SERVER_PORT:8080}

spring:
  application:
    name: eden-research
  threads.virtual:
    enabled: true
  ai:
    mcp:
      server:
        name: nip-server
        version: 0.0.1
        type: async
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
        protocol: streamable
        streamable-http:
          mcp-endpoint: /mcp

management:
  info.git:
    enabled: true
    mode: full
  endpoints:
    web.exposure.include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}

app:
  web:
    jira-url: https://paramount.atlassian.net
    regon-url: https://wyszukiwarkaregon.stat.gov.pl
  regon:
    api-key: ${REGON_API_KEY:abcde12345abcde12345}


logging:
  #structured.format.console: ecs
  level:
    root: INFO
    org.springframework.web: DEBUG
    tech.paramount: DEBUG
