server.port: 8080

spring:
  application:
    name: eden-research
  threads.virtual:
    enabled: true
  mvc.problemdetails:
    enabled: true

management:
  info.git:
    enabled: true
    mode: full
  endpoints:
    web.exposure.include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}

app:
  web:
    jira-url: https://paramount.atlassian.net
    regon-url: https://wyszukiwarkaregon.stat.gov.pl
  regon:
    api-key: ${REGON_API_KEY:abcde12345abcde12345}


logging:
  structured.format.console: ecs
  level:
    root: INFO
    org.springframework.web: DEBUG
    pl.michalkowol: DEBUG
